name: Build

on:
  push: 
    branches: main
  pull_request:
    branches: main

jobs:
  build-release: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Setup C++ Environment (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential ninja-build python3
      - name: Setup C++ Environment (macOS)
        if: runner.os == 'macOS'
        run: brew update && brew install ninja meson
      - name: Setup C++ Environment (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja meson 

      - name: Setup Meson (Linux)
        if: runner.os == 'Linux'
        run: |
          python3 -m pip install --user meson
          meson --version
        
      - name: Configure meson
        run: |
          mkdir include
          meson setup build -Dbuildtype=release -Ddefault_library=static

      - name: Build
        run: meson compile -C build
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}-release-build
          path: build/bin
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Setup C++ Environment
        run: sudo apt-get update && sudo apt-get install -y build-essential ninja-build libasio-dev clang-tidy cppcheck catch2 python3

      - name: Setup meson
        run: |
          python3 -m pip install --user meson
          meson --version
          
      - name: Configure meson
        run: |
          mkdir include
          meson setup build -Dbuildtype=debugoptimized -Ddefault_library=shared

      - name: Build
        run: meson compile -C build

      - name: Unit Test
        run: meson test -C build --verbose
        continue-on-error: true

      - name: Run clang-tidy
        run: clang-tidy -p build src/**/*.cpp --config-file=".clang-tidy"
        continue-on-error: true

      - name: Run CppCheck
        run: cppcheck --enable=all --inconclusive --project=build/compile_commands.json -I src/pch.h --suppress=missingIncludeSystem --suppress=missingInclude
        continue-on-error: true
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ubuntu-debug-build
          path: build/bin
